export const GET_STOCKS_REQUEST = "GET_STOCKS_REQUEST";
export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const GET_STOCKS_FAIL = "GET_STOCKS_FAIL";


export const GET_STOCK_DETAILS_REQUEST = "GET_STOCK_DETAILS_REQUEST";
export const GET_STOCK_DETAILS_SUCCESS = "GET_STOCK_DETAILS_SUCCESS";
export const GET_STOCK_DETAILS_FAIL = "GET_STOCK_DETAILS_FAIL";


export const GET_TOP_STOCKS_REQUEST = "GET_TOP_STOCKS_REQUEST";
export const GET_TOP_STOCKS_SUCCESS = "GET_TOP_STOCKS_SUCCESS";
export const GET_TOP_STOCKS_FAIL = "GET_TOP_STOCKS_FAIL";


export const SEARCH_STOCKS_REQUEST = "SEARCH_STOCKS_REQUEST";
export const SEARCH_STOCKS_SUCCESS = "SEARCH_STOCKS_SUCCESS";
export const SEARCH_STOCKS_FAIL = "SEARCH_STOCKS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";